#!/bin/bash

set -euo pipefail

GRUB_CFG="/etc/default/grub.d/98_realtime.cfg"
EXTRA_CMDLINE=""   # applied to every platform except hamoa

# Detection order matters: rb3lite before rb3 (both DT models contain "rb3gen2").
PLATFORMS=(hamoa rb8 amr rb4 monza2 rb3lite rb3)

# Device-tree model regex per platform (used only for auto-detection).
PLATFORM_REGEX_hamoa='hamoa'
PLATFORM_REGEX_rb8='9075'
PLATFORM_REGEX_amr='lemans amr'
PLATFORM_REGEX_rb4='iq8 8275'
PLATFORM_REGEX_monza2='monza'
PLATFORM_REGEX_rb3lite='qcs5430 fp1'
PLATFORM_REGEX_rb3='robotics rb3gen2'

# Per-platform CPU parameters.
configure_platform() {
    case "$PLATFORM" in
        hamoa)
            RT_CPU=11
            CYCLICTEST_CPU=10
            TOTAL_CPUS=12
            HOUSEKEEP="0-10"
            IRQ_MASK="7ff"
            LABEL="Hamoa"
            ;;
        rb8)
            RT_CPU=7
            CYCLICTEST_CPU=6
            TOTAL_CPUS=8
            HOUSEKEEP="0-6"
            IRQ_MASK="7f"
            LABEL="RB8"
            ;;
        amr)
            # Same configuration as rb8.
            RT_CPU=7
            CYCLICTEST_CPU=6
            TOTAL_CPUS=8
            HOUSEKEEP="0-6"
            IRQ_MASK="7f"
            LABEL="AMR"
            ;;
        rb4)
            RT_CPU=3
            CYCLICTEST_CPU=2
            TOTAL_CPUS=8
            HOUSEKEEP="0-2,4-7"
            IRQ_MASK="f7"
            LABEL="RB4"
            ;;
        monza2)
            # Same configuration as rb4.
            RT_CPU=3
            CYCLICTEST_CPU=2
            TOTAL_CPUS=8
            HOUSEKEEP="0-2,4-7"
            IRQ_MASK="f7"
            LABEL="Monza2"
            ;;
        rb3lite)
            RT_CPU=5
            CYCLICTEST_CPU=4
            TOTAL_CPUS=6
            HOUSEKEEP="0-4"
            IRQ_MASK="1f"
            LABEL="RB3 Gen2 Lite"
            ;;
        rb3)
            # Same configuration as rb8.
            RT_CPU=7
            CYCLICTEST_CPU=6
            TOTAL_CPUS=8
            HOUSEKEEP="0-6"
            IRQ_MASK="7f"
            LABEL="RB3 Gen2"
            ;;
        *)
            echo "ERROR: unknown platform '$PLATFORM'. Use -p <${PLATFORMS[*]}>"
            exit 1
            ;;
    esac
}

# Write a value to every writable file matching the given globs.
write() {
    local value="$1"; shift
    local f
    for f in "$@"; do
        [[ -w "$f" ]] && echo "$value" > "$f" 2>/dev/null || true
    done
}

# Detect the platform (unless overridden) and load its parameters.
detect_platform() {
    DT_MODEL=""
    local f
    for f in /proc/device-tree/model /sys/firmware/devicetree/base/model; do
        [[ -r "$f" ]] && { DT_MODEL=$(tr -d '\0' < "$f"); break; }
    done

    if [[ -z "$PLATFORM" ]]; then
        local key regex_var
        for key in "${PLATFORMS[@]}"; do
            regex_var="PLATFORM_REGEX_${key}"
            grep -qiE "${!regex_var}" <<<"$DT_MODEL" && { PLATFORM="$key"; break; }
        done
    fi

    if [[ -z "$PLATFORM" ]]; then
        echo "ERROR: could not detect platform. Use -p <${PLATFORMS[*]}>"
        [[ -n "$DT_MODEL" ]] && echo "       DT model: $DT_MODEL"
        exit 1
    fi

    configure_platform
}

cmd_setup() {
    echo "==> RT setup — $LABEL"
    apt-get install -y linux-qcom-rt

    mkdir -p /etc/default/grub.d
    local extra=""
    [[ "$PLATFORM" != hamoa ]] && extra=" $EXTRA_CMDLINE"
    cat > "$GRUB_CFG" <<EOF
# Generated by rt.sh for $LABEL
GRUB_CMDLINE_LINUX="\${GRUB_CMDLINE_LINUX} rcu_nocbs=$RT_CPU isolcpus=$RT_CPU irqaffinity=$HOUSEKEEP$extra"
EOF
    update-grub

    echo "GRUB updated. Rebooting in 5s (run '${0##*/} test' afterwards)..."
    sleep 5
    reboot
}

STRESS_PIDS=()

start_stress() {
    [[ -z "$STRESS_LOAD" ]] && return 0
    command -v stress-ng &>/dev/null || apt-get install -y stress-ng
    trap stop_stress EXIT INT TERM
    local c
    for c in $(seq 0 $((TOTAL_CPUS - 1))); do
        [[ "$c" -eq "$RT_CPU" ]] && continue
        taskset -c "$c" stress-ng --cpu 1 --cpu-load "$STRESS_LOAD" \
            -t "${TEST_MINUTES}m" &>/dev/null &
        STRESS_PIDS+=("$!")
    done
}

stop_stress() {
    [[ ${#STRESS_PIDS[@]} -eq 0 ]] && return 0
    kill "${STRESS_PIDS[@]}" 2>/dev/null || true
    STRESS_PIDS=()
}

cmd_test() {
    echo "==> RT test — $LABEL, ${TEST_MINUTES} min"

    uname -r | grep -qiE 'rt|PREEMPT_RT' || {
        echo "ERROR: not running an RT kernel ($(uname -r)). Run '${0##*/} setup' first."
        exit 1
    }

    # Runtime tuning (resets on reboot).
    write performance /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
    write 1           /sys/devices/system/cpu/cpu*/cpuidle/state*/disable
    write 0           /sys/kernel/tracing/tracing_on
    write 0           /proc/sys/kernel/timer_migration
    write "$IRQ_MASK" /sys/devices/virtual/workqueue/*/cpumask
    write -1          /proc/sys/kernel/sched_rt_runtime_us
    systemctl stop irqbalanced 2>/dev/null || true
    write "$IRQ_MASK" /proc/irq/[0-9]*/smp_affinity

    command -v cyclictest &>/dev/null || apt-get install -y rt-tests

    local json="rt_${PLATFORM}_$(date +%Y%m%d_%H%M%S).json"
    local opts=(-a "$RT_CPU" -t 1 -m -p 99 -i 1000
                -l "$((TEST_MINUTES * 60 * 1000))" --json="$json"
                --mainaffinity="$CYCLICTEST_CPU")
    [[ "$VERBOSE" == true ]] || opts+=(-q)
    [[ ${#EXTRA_ARGS[@]} -gt 0 ]] && opts+=("${EXTRA_ARGS[@]}")

    start_stress
    echo "==> Running: cyclictest ${opts[*]}"
    cyclictest "${opts[@]}" || true
    stop_stress

    echo "==> Done. Result: $json"
}

usage() {
    cat <<EOF
Usage: sudo ${0##*/} <setup|test> [options]

  setup    Install linux-qcom-rt, configure cmdline for CPU isolation, reboot.
  test     Apply runtime tuning and run cyclictest.

Options (test):
  -p, --platform <name>   Override auto-detection (${PLATFORMS[*]}).
  -t, --time <minutes>    cyclictest duration (default 60).
  -l, --load [pct]        stress-ng background load on housekeeping CPUs (default 60).
  -v, --verbose           Live cyclictest output instead of quiet summary.
  -h, --help              Show this help.
  -- <args...>            Pass any extra arguments to cyclictest.
EOF
    exit 1
}

COMMAND=""
PLATFORM=""
TEST_MINUTES=60
VERBOSE=false
STRESS_LOAD=""
EXTRA_ARGS=()

[[ $# -eq 0 ]] && usage
case "$1" in
    setup|test) COMMAND="$1"; shift ;;
    -h|--help)  usage ;;
    *) echo "ERROR: unknown command '$1'"; usage ;;
esac

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p|--platform)     PLATFORM="${2,,}"; shift 2 ;;
        -t|--time)         TEST_MINUTES="$2"; shift 2 ;;
        -v|--verbose)      VERBOSE=true; shift ;;
        -l|--load)
            if [[ "${2:-}" =~ ^[0-9]+$ ]]; then STRESS_LOAD="$2"; shift 2
            else STRESS_LOAD=60; shift; fi
            ;;
        --) shift; EXTRA_ARGS=("$@"); break ;;
        -h|--help) usage ;;
        *) echo "ERROR: unknown argument '$1'"; usage ;;
    esac
done

[[ $EUID -eq 0 ]] || { echo "ERROR: run as root (sudo)."; exit 1; }
detect_platform

case "$COMMAND" in
    setup) cmd_setup ;;
    test)  cmd_test ;;
esac
