#!/bin/bash
# ==============================================================================
# RT Test Setup — Part 1 (Pre-Reboot)
# Run this script once on the target device before rebooting.
#
# Usage: sudo ./rt_setup_pre_reboot.sh --board <rb8|rb4|hamoa>
#
# What it does:
#   1. Installs linux-qcom-rt kernel
#   2. Configures GRUB for CPU isolation
#   3. Reboots
#
# After reboot, run: sudo ./rt_setup_post_reboot.sh --board <board> --hours <N>
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# Board Configurations
# ------------------------------------------------------------------------------

configure_board() {
    case "${BOARD}" in
        rb8)
            RT_CPU=7
            HOUSEKEEP_RANGE="0-6"
            BOARD_LABEL="RB8"
            ;;
        rb4)
            RT_CPU=3
            HOUSEKEEP_RANGE="0-2,4-7"
            BOARD_LABEL="RB4"
            ;;
        hamoa)
            RT_CPU=11
            HOUSEKEEP_RANGE="0-10"
            BOARD_LABEL="Hamoa (IQ-X7181)"
            ;;
        *)
            echo "ERROR: Unknown board '${BOARD}'. Supported: rb8, rb4, hamoa"
            exit 1
            ;;
    esac

    echo "Board          : ${BOARD_LABEL}"
    echo "RT CPU         : ${RT_CPU}"
    echo "Housekeeping   : CPUs ${HOUSEKEEP_RANGE}"
    echo ""
}

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

check_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        echo "ERROR: This script must be run as root (sudo)."
        exit 1
    fi
}

log() {
    echo "[$(date '+%H:%M:%S')] $*"
}

# ------------------------------------------------------------------------------
# Step 1: Install RT kernel
# ------------------------------------------------------------------------------

step_install() {
    log "==> Step 1: Installing RT kernel..."
    apt-get install -y linux-qcom-rt
    log "RT kernel installed."
}

# ------------------------------------------------------------------------------
# Step 2: Configure GRUB
# ------------------------------------------------------------------------------

step_grub() {
    log "==> Step 2: Configuring GRUB for CPU isolation..."

    local cfg="/etc/default/grub.d/98_realtime.cfg"
    mkdir -p /etc/default/grub.d

    cat > "${cfg}" << EOF
# Generated by rt_setup_pre_reboot.sh for board: ${BOARD_LABEL}
GRUB_CMDLINE_LINUX="\${GRUB_CMDLINE_LINUX} rcu_nocbs=${RT_CPU} isolcpus=${RT_CPU} irqaffinity=${HOUSEKEEP_RANGE}"
EOF

    log "GRUB config written:"
    cat "${cfg}"

    log "Running update-grub..."
    update-grub
    log "GRUB updated."
}

# ------------------------------------------------------------------------------
# Argument parsing
# ------------------------------------------------------------------------------

usage() {
    cat <<EOF
Usage: sudo $0 --board <rb8|rb4|hamoa>

Boards:
  rb8     Snapdragon RB8  — 8  CPUs (0-7),  RT CPU=7,  housekeeping=0-6
  rb4     Snapdragon RB4  — 8  CPUs (0-7),  RT CPU=3,  housekeeping=0-2,4-7
  hamoa   Hamoa/IQ-X7181  — 12 CPUs (0-11), RT CPU=11, housekeeping=0-10

After this script completes and the system reboots, run:
  sudo ./rt_setup_post_reboot.sh --board <board> --hours <N>
EOF
    exit 1
}

BOARD=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --board) BOARD="${2,,}"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown argument: $1"; usage ;;
    esac
done

[[ -z "${BOARD}" ]] && { echo "ERROR: --board is required."; usage; }

check_root
configure_board

echo "=================================================="
echo " RT Setup Part 1 (Pre-Reboot)  |  Board: ${BOARD_LABEL}"
echo "=================================================="
echo ""

step_install
step_grub

echo ""
log "All done. Rebooting in 5 seconds..."
log "After reboot, run: sudo ./rt_setup_post_reboot.sh --board ${BOARD} --hours <N>"
sleep 5
reboot
